x-typebot-common: &typebot-common
  networks:
    - network_public
  environment: &typebot-env
    - DATABASE_URL=postgresql://postgres:secret@postgres:5432/typebot

    - ENCRYPTION_SECRET=secret

    - DEFAULT_WORKSPACE_PLAN=UNLIMITED
    - NEXTAUTH_URL=https://builder.bot.website.com
    - NEXT_PUBLIC_VIEWER_URL=https://bot.website.com
    - NEXTAUTH_URL_INTERNAL=http://localhost:3000

    - DISABLE_SIGNUP=true

    - ADMIN_EMAIL=example@example.com
    - NEXT_PUBLIC_SMTP_FROM='Typebot' <no-reply@website.com>
    - SMTP_AUTH_DISABLED=true
    # - SMTP_HOST=smtp.sendgrid.net
    # - SMTP_PORT=587
    # - SMTP_USERNAME=user
    # - SMTP_PASSWORD=secret
    # - SMTP_SECURE=true

    # - NEXT_PUBLIC_GOOGLE_API_KEY=xxx
    # - GOOGLE_CLIENT_ID=xxx
    # - GOOGLE_CLIENT_SECRET=xxx

    # - S3_ACCESS_KEY=xxx
    # - S3_SECRET_KEY=xxx
    # - S3_BUCKET=website.com-typebot
    # - S3_REGION=us-east-1
    # - S3_ENDPOINT=s3.us-east-1.amazonaws.com

    # - NEXT_PUBLIC_GIPHY_API_KEY=xxx
  deploy: &typebot-deploy
    mode: replicated
    replicas: 1
    placement:
      constraints:
        - node.role == manager
    resources:
      limits:
        cpus: "0.5"
        memory: 768M

services:
  typebot_builder:
    <<: *typebot-common
    image: baptistearno/typebot-builder:latest
    deploy:
      <<: *typebot-deploy
      labels:
        - traefik.enable=true
        - traefik.http.routers.typebot_builder.rule=Host(`builder.bot.website.com`)
        - traefik.http.routers.typebot_builder.entrypoints=websecure
        - traefik.http.routers.typebot_builder.tls.certresolver=letsencryptresolver
        - traefik.http.services.typebot_builder.loadbalancer.server.port=3000
        - traefik.http.services.typebot_builder.loadbalancer.passHostHeader=true
        - traefik.http.routers.typebot_builder.service=typebot_builder

  typebot_viewer:
    <<: *typebot-common
    image: baptistearno/typebot-viewer:latest
    deploy:
      <<: *typebot-deploy
      labels:
        - traefik.enable=true
        - traefik.http.routers.typebot_viewer.rule=Host(`bot.website.com`)
        - traefik.http.routers.typebot_viewer.entrypoints=websecure
        - traefik.http.routers.typebot_viewer.tls.certresolver=letsencryptresolver
        - traefik.http.services.typebot_viewer.loadbalancer.server.port=3000
        - traefik.http.services.typebot_viewer.loadbalancer.passHostHeader=true
        - traefik.http.routers.typebot_viewer.service=typebot_viewer

networks:
  network_public:
    external: true
    name: network_public
